package nextstep.qna.domain;

import nextstep.qna.CannotDeleteException;
import nextstep.users.domain.NsUserTest;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThatThrownBy;

public class AnswerTest {
    public static final Answer A1 = new Answer(NsUserTest.JAVAJIGI, QuestionTest.Q1, "Answers Contents1");
    public static final Answer A2 = new Answer(NsUserTest.SANJIGI, QuestionTest.Q1, "Answers Contents2");

    @Test
    @DisplayName("답변자가 다르다면 예외를 throw")
    void deleteTest2() {
        List<DeleteHistory> deleteHistories = new ArrayList<>();
        assertThatThrownBy(() -> A1.delete(NsUserTest.SANJIGI, deleteHistories)).isInstanceOf(CannotDeleteException.class);
    }
}
